{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-env
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.labels "context" $ ) | nindent 4 }}
  {{- if .Values.externalSecrets.enabled }}
  annotations:
    avp.kubernetes.io/path: {{ .Values.externalSecrets.path | quote }}
  {{- end }}
type: Opaque
{{- if .Values.externalSecrets.enabled }}
stringData:
{{- else }}
data:
{{- end }}
  {{- if .Values.auth.token }}
  TRACKER_TOKEN: {{ include "secret.value" (dict "key" "TRACKER_TOKEN" "value" .Values.auth.token "avp" .Values.externalSecrets.enabled) }}
  {{- end }}
  {{- if .Values.auth.iamToken }}
  TRACKER_IAM_TOKEN: {{ include "secret.value" (dict "key" "TRACKER_IAM_TOKEN" "value" .Values.auth.iamToken "avp" .Values.externalSecrets.enabled) }}
  {{- end }}
  {{- if .Values.auth.serviceAccount.keyId }}
  TRACKER_SA_KEY_ID: {{ include "secret.value" (dict "key" "TRACKER_SA_KEY_ID" "value" .Values.auth.serviceAccount.keyId "avp" .Values.externalSecrets.enabled) }}
  TRACKER_SA_SERVICE_ACCOUNT_ID: {{ include "secret.value" (dict "key" "TRACKER_SA_SERVICE_ACCOUNT_ID" "value" .Values.auth.serviceAccount.serviceAccountId "avp" .Values.externalSecrets.enabled) }}
  TRACKER_SA_PRIVATE_KEY: {{ include "secret.value" (dict "key" "TRACKER_SA_PRIVATE_KEY" "value" .Values.auth.serviceAccount.privateKey "avp" .Values.externalSecrets.enabled) }}
  {{- end }}
  {{- if .Values.redis.auth.password }}
  REDIS_PASSWORD: {{ include "secret.value" (dict "key" "REDIS_PASSWORD" "value" .Values.redis.auth.password "avp" .Values.externalSecrets.enabled) }}
  {{- else if .Values.externalRedis.password }}
  REDIS_PASSWORD: {{ include "secret.value" (dict "key" "REDIS_PASSWORD" "value" .Values.externalRedis.password "avp" .Values.externalSecrets.enabled) }}
  {{- end }}
  {{- if .Values.oauth.enabled }}
  OAUTH_CLIENT_SECRET: {{ include "secret.value" (dict "key" "OAUTH_CLIENT_SECRET" "value" .Values.oauth.clientSecret "avp" .Values.externalSecrets.enabled) }}
  {{- if .Values.oauth.encryptionKeys }}
  OAUTH_ENCRYPTION_KEYS: {{ include "secret.value" (dict "key" "OAUTH_ENCRYPTION_KEYS" "value" .Values.oauth.encryptionKeys "avp" .Values.externalSecrets.enabled) }}
  {{- end }}
  {{- end }}
{{- end }}
